stages:
  - trigger

backend:
  stage: trigger
  trigger:
    include:
      - local: .gitlab/backend.yml
  rules:
    - changes:
        - backend/**/*
        - .gitlab/backend.yml
        - .gitlab-ci.yml

frontend:
  stage: trigger
  trigger:
    include:
      - local: .gitlab/frontend.yml
  rules:
    - changes:
        - frontend/**/*
        - .gitlab/frontend.yml
        - .gitlab-ci.yml
