stages:
  - install
  - check
  - test
  - build

cache:
  key: "${CI_COMMIT_REF_SLUG}-backend"
  paths:
    - backend/.m2/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/backend/.m2/repository"

backend-install:
  stage: install
  image: maven:3.9.9-eclipse-temurin-17
  before_script:
    - cd backend
  script:
    - mvn dependency:resolve
  cache:
    key: "${CI_COMMIT_REF_SLUG}-backend"
    paths:
      - backend/.m2/
    policy: pull-push

backend-checkstyle:
  stage: check
  image: maven:3.9.9-eclipse-temurin-17
  before_script:
    - cd backend
  script:
    - mvn checkstyle:check
  cache:
    key: "${CI_COMMIT_REF_SLUG}-backend"
    paths:
      - backend/.m2/
    policy: pull-push

backend-test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-17
  before_script:
    - cd backend
  script:
    - mvn test
  artifacts:
    when: always
    reports:
      junit:
        - backend/target/surefire-reports/TEST-*.xml
  cache:
    key: "${CI_COMMIT_REF_SLUG}-backend"
    paths:
      - backend/.m2/
    policy: pull-push

backend-build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-17
  before_script:
    - cd backend
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar
  cache:
    key: "${CI_COMMIT_REF_SLUG}-backend"
    paths:
      - backend/.m2/
    policy: pull
