server:
  port: 8080

spring:
  application:
    name: campus-help
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  secret: Y2FtcHVzLWhlbHAtc2VjcmV0LWtleS0yMDI2LW1heS1zZWN1cmUtYW5kLWxvbmc=
  expiration: 86400000
